# German translations for minarca_client.
# Copyright (C) 2023 ORGANIZATION
# This file is distributed under the same license as the minarca_client
# project.
# FIRST AUTHOR michael@einzelfabrik.de, 2023.
#
msgid ""
msgstr ""
"Project-Id-Version: minarca_client 5.0.1.dev2+g647e551\n"
"Report-Msgid-Bugs-To: michael@einzelfabrik.de\n"
"POT-Creation-Date: 2024-12-05 14:16-0500\n"
"PO-Revision-Date: 2023-11-22 17:29+0100\n"
"Last-Translator: Michael Nitzsche michael@einzelfabrik.de\n"
"Language: de\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.16.0\n"

#: minarca_client/main.py:62
msgid "Operation aborted by the user."
msgstr "Operation durch den Benutzer abgebrochen."

#: minarca_client/main.py:71
msgid "yes"
msgstr "ja"

#: minarca_client/main.py:71
msgid "y"
msgstr "j"

#: minarca_client/main.py:80
#, python-format
msgid "new version %s available"
msgstr "neue Version %s verfügbar"

#: minarca_client/main.py:82
msgid "fail to check for latest version"
msgstr "Fehler beim Überprüfen der neuesten Version"

#: minarca_client/main.py:96
msgid "unexpected error during backup"
msgstr ""

#: minarca_client/main.py:103
#, fuzzy
msgid "Backup Instances:"
msgstr "Backup ist veraltet"

#: minarca_client/main.py:105 minarca_client/main.py:421
#: minarca_client/ui/backup_card.py:21
msgid "No name"
msgstr ""

#: minarca_client/main.py:107
#, fuzzy
msgid "Are you sure you want to forget the above backup settings? (Yes/No): "
msgstr "Sind Sie sicher, dass Sie den Backup-Job anhalten möchten?"

#: minarca_client/main.py:125
msgid ""
"Do you want to backup to a local device (external disk or network share)?"
" (Yes/No): "
msgstr ""

#: minarca_client/main.py:131
msgid "Enter the local destination path: "
msgstr ""

#: minarca_client/main.py:151
#, fuzzy
msgid "Remote URL (e.g.: https://backup.examples.com): "
msgstr "URL zum entfernten minarca-Server, z.B.: http://example.com:8080/"

#: minarca_client/main.py:153
#, fuzzy
msgid "Username: "
msgstr "Benutzername:"

#: minarca_client/main.py:155
#, fuzzy
msgid "Password or access token: "
msgstr "Passwort oder Zugriffstoken: "

#: minarca_client/main.py:172 minarca_client/main.py:177
msgid "Linked successfully"
msgstr "Erfolgreich verknüpft"

#: minarca_client/main.py:175
#, fuzzy
msgid "Do you want to replace the existing repository? (Yes/No): "
msgstr "Möchten Sie das bestehende Repository ersetzen?"

#: minarca_client/main.py:195
msgid ""
"To update include or exclude patterns, you must configure at least one "
"backup instance."
msgstr ""

#: minarca_client/main.py:282
msgid "From which backup source do you want to restore data from?"
msgstr ""

#: minarca_client/main.py:294
#, fuzzy
msgid "Enter backup instance ID: "
msgstr "Backup ist veraltet"

#: minarca_client/main.py:298
#, python-format
msgid "Invalid instance ID: %s"
msgstr ""

#: minarca_client/main.py:302
msgid "Your instance value doesn't match any backup instances"
msgstr ""

#: minarca_client/main.py:304
msgid "Your instance value matches too many backup instances"
msgstr ""

#: minarca_client/main.py:317
#, fuzzy, python-format
msgid "Do you want to restore %s? (Yes/No): "
msgstr "Möchten Sie %s wiederherstellen (Ja/Nein): "

#: minarca_client/main.py:331
msgid ""
"Are you sure you want to proceed with the restore operation? Please note "
"that this will override your current data. (Yes/No): "
msgstr ""
"Sind Sie sicher, dass Sie mit der Wiederherstellung fortfahren möchten? "
"Bitte beachten Sie, dass dies Ihre aktuellen Daten überschreiben wird. "
"(Ja/Nein): "

#: minarca_client/main.py:355
msgid "backup not running"
msgstr "Backup läuft nicht"

#: minarca_client/main.py:421
#, fuzzy, python-format
msgid "Backup Instance: %s"
msgstr "Backup ist veraltet"

#: minarca_client/main.py:425
#, fuzzy, python-format
msgid "Identifier:             %s"
msgstr "Details:                  %s"

#: minarca_client/main.py:427
#, python-format
msgid "Remote server:          %s"
msgstr "Remote-Server:          %s"

#: minarca_client/main.py:429
#, fuzzy, python-format
msgid "Local device:           %s"
msgstr "Pausiert bis:            %s"

#: minarca_client/main.py:430
#, python-format
msgid "Connectivity status:    %s"
msgstr "Konnektivitätsstatus:   %s"

#: minarca_client/main.py:430
#, fuzzy
msgid "Connected"
msgstr "Trennen"

#: minarca_client/main.py:430
#, fuzzy
msgid "Not connected"
msgstr "Trennen"

#: minarca_client/main.py:433
#, python-format
msgid "Last successful backup: %s"
msgstr "Letztes erfolgreiches Backup: %s"

#: minarca_client/main.py:434 minarca_client/main.py:439
#: minarca_client/main.py:441 minarca_client/ui/backup_settings.py:253
msgid "Never"
msgstr "Nie"

#: minarca_client/main.py:438
#, python-format
msgid "Last backup date:       %s"
msgstr "Letztes Backup-Datum:       %s"

#: minarca_client/main.py:441
#, python-format
msgid "Last backup status:     %s"
msgstr "Status des letzten Backups: %s"

#: minarca_client/main.py:443
#, python-format
msgid "Details:                %s"
msgstr "Details:                  %s"

#: minarca_client/main.py:445
#, python-format
msgid "Paused until:           %s"
msgstr "Pausiert bis:            %s"

#: minarca_client/main.py:470
#, fuzzy
msgid "Minarca"
msgstr "Minarca Konfiguration"

#: minarca_client/main.py:471
msgid "Application failed to start"
msgstr ""

#: minarca_client/main.py:472
msgid ""
"If the problem persists, check the logs with your administrator or try "
"reinstalling the application."
msgstr ""

#: minarca_client/main.py:493
msgid ""
"Minarca manages your computer's backup by linking your computer with a "
"centralized server and running backups on a given schedule."
msgstr ""
"Minarca verwaltet das Backup Ihres Computers, indem es Ihren Computer mit"
" einem zentralen Server verknüpft und Backups nach einem festgelegten "
"Zeitplan ausführt."

#: minarca_client/main.py:512
msgid "start a backup in background mode"
msgstr "Starten Sie ein Backup im Hintergrundmodus"

#: minarca_client/main.py:513 minarca_client/main.py:525
msgid "force execution of a backup even if it's not time to run"
msgstr ""
"erzwinge die Ausführung eines Backups, selbst wenn es nicht an der Zeit "
"ist, dieses auszuführen"

#: minarca_client/main.py:517 minarca_client/main.py:529
msgid "Limit backup to the given instance(s)."
msgstr ""

#: minarca_client/main.py:524
msgid "start a backup in foreground mode"
msgstr "Starten Sie ein Backup im Vordergrundmodus"

#: minarca_client/main.py:536
msgid "exclude files from being backed up"
msgstr "Dateien ausschließen, die gesichert werden sollen"

#: minarca_client/main.py:540
msgid "Add exclude file pattern to the given instance(s)."
msgstr ""

#: minarca_client/main.py:544 minarca_client/main.py:557
msgid "file pattern to be excluded. May contain `*` or `?` wildcard"
msgstr ""
"Dateimuster, das ausgeschlossen werden soll. Kann Platzhalter `*` oder "
"`?` enthalten"

#: minarca_client/main.py:549
msgid "include files to be backed up"
msgstr "Dateien einschließen, die gesichert werden sollen"

#: minarca_client/main.py:553
msgid "Add include file pattern to the given instance(s)."
msgstr ""

#: minarca_client/main.py:563
msgid "configure this agent to backup to a new destination (remote or local)"
msgstr ""

#: minarca_client/main.py:565
#, fuzzy
msgid "URL to the remote server. e.g.: http://example.com:8080/"
msgstr "URL zum entfernten minarca-Server, z.B.: http://example.com:8080/"

#: minarca_client/main.py:566
#, fuzzy
msgid "username to be used for authentication with the remote server"
msgstr "Benutzername, der für die Authentifizierung verwendet werden soll"

#: minarca_client/main.py:570
msgid ""
"password or access token to use for authentication. You will be prompted "
"if not provided"
msgstr ""
"Passwort oder Zugriffstoken zur Authentifizierung. Wird bei fehlender "
"Angabe abgefragt"

#: minarca_client/main.py:572
msgid "repository name to be used"
msgstr "Name des zu verwendenden Repositorys"

#: minarca_client/main.py:576
msgid ""
"replace existing repository on backup destination if it exists without "
"confirmation"
msgstr ""

#: minarca_client/main.py:578
#, fuzzy
msgid "path to local destination"
msgstr "Partielle Wiederherstellung"

#: minarca_client/main.py:582
msgid "list the include/exclude patterns"
msgstr "Liste der Ein-/Ausschlussmuster anzeigen"

#: minarca_client/main.py:586
msgid "Show include and exclude patterns only for the given instance(s)."
msgstr ""

#: minarca_client/main.py:593
msgid "restore data from backup"
msgstr "Daten aus Backup wiederherstellen"

#: minarca_client/main.py:597
msgid "Force the use of a given instance for restore."
msgstr ""

#: minarca_client/main.py:603
msgid ""
"Date and time to be restored. Could be 'now' to restore the latest "
"backup. Could be an epoch value like '1682367069'. Could be an ISO date "
"format like '2023-02-24T04:11:09-04:00'. Could be an interval like '3D' "
"for 3 days ago."
msgstr ""
"Datum und Uhrzeit der Wiederherstellung. Kann 'now' sein, um das neueste "
"Backup wiederherzustellen. Kann ein Epoch-Wert wie '1682367069' sein. "
"Kann ein ISO-Datumsformat sein wie '2023-02-24T04:11:09-04:00'. Kann ein "
"Intervall wie '3D' für vor 3 Tagen sein."

#: minarca_client/main.py:609
msgid ""
"Define an alternate location to restore files or folders instead of "
"restoring them in place."
msgstr ""

#: minarca_client/main.py:614
#, fuzzy
msgid "Force execution of restore operation without confirmation from the user."
msgstr ""
"erzwinge die Ausführung der Wiederherstellung ohne Bestätigung durch den "
"Benutzer"

#: minarca_client/main.py:616
msgid "files and folders to be restored"
msgstr "Dateien und Ordner, die wiederhergestellt werden sollen"

#: minarca_client/main.py:620
msgid "stop the backup"
msgstr "Backup stoppen"

#: minarca_client/main.py:624
msgid "Stop only the given instance(s)."
msgstr ""

#: minarca_client/main.py:628
msgid "doesn't fail if the backup is not running."
msgstr "fehlschlägt nicht, wenn das Backup nicht läuft"

#: minarca_client/main.py:633
#, fuzzy
msgid "create the required scheduled task in Windows Task Scheduler"
msgstr ""
"Erforderliche geplante Aufgabe in crontab oder Windows Taskplaner "
"erstellen"

#: minarca_client/main.py:635
#, fuzzy
msgid "create the required scheduled task in launchd"
msgstr ""
"Erforderliche geplante Aufgabe in crontab oder Windows Taskplaner "
"erstellen"

#: minarca_client/main.py:637
#, fuzzy
msgid "create the required scheduled task in crontab"
msgstr ""
"Erforderliche geplante Aufgabe in crontab oder Windows Taskplaner "
"erstellen"

#: minarca_client/main.py:644
msgid "schedule backup to run hourly"
msgstr "Backup stündlich planen"

#: minarca_client/main.py:651
msgid "schedule backup to run daily"
msgstr "Backup täglich planen"

#: minarca_client/main.py:658
msgid "schedule backup to run weekly"
msgstr "Backup wöchentlich planen"

#: minarca_client/main.py:663
msgid "Configure only the given instance(s)."
msgstr ""

#: minarca_client/main.py:668
msgid "username required to run task when the user is logged out"
msgstr ""
"Benutzername erforderlich, um die Aufgabe auszuführen, wenn der Benutzer "
"abgemeldet ist"

#: minarca_client/main.py:669
msgid "password required to run task when the user is logged out"
msgstr ""
"Passwort erforderlich, um Aufgabe auszuführen, wenn Benutzer abgemeldet "
"ist"

#: minarca_client/main.py:673
msgid "return the current Minarca status"
msgstr "Aktuellen minarca-Status zurückgeben"

#: minarca_client/main.py:677
msgid "Show status for the given instance(s)."
msgstr ""

#: minarca_client/main.py:684
#, fuzzy
msgid "forget backup settings"
msgstr "Noch kein Backup"

#: minarca_client/main.py:688
msgid "Forget settings of the given backup instance(s)."
msgstr ""

#: minarca_client/main.py:693
#, fuzzy
msgid "Force forget operation without confirmation from the user."
msgstr ""
"erzwinge die Ausführung der Wiederherstellung ohne Bestätigung durch den "
"Benutzer"

#: minarca_client/main.py:700
msgid ""
"temporarily delay the execution of the backup for the given number of "
"hours. Default is 24 hours."
msgstr ""
"Ausführung des Backups vorübergehend für die angegebene Stundenanzahl "
"verzögern. Standard 24 Stunden."

#: minarca_client/main.py:705
msgid "Pause only the given instance(s)."
msgstr ""

#: minarca_client/main.py:709
msgid "number of hours"
msgstr "Anzahl Stunden"

#: minarca_client/main.py:714
msgid "clear previously set delay"
msgstr "Zuvor festgelegte Verzögerung aufheben"

#: minarca_client/main.py:723
msgid "verify backup integrity"
msgstr ""

#: minarca_client/main.py:727
msgid "Verify backup integrity of the given backup instance(s)."
msgstr ""

#: minarca_client/main.py:734
msgid "open graphical user interface (default when calling minarcaw)"
msgstr "Grafische Benutzeroberfläche öffnen (Standard bei Aufruf von minarcaw)"

#: minarca_client/main.py:806
#, fuzzy
msgid "Process interrupted by user."
msgstr "Wiederherstellung wurde unterbrochen"

#: minarca_client/core/exceptions.py:71
#, python-format
msgid "No backup instances match: %s"
msgstr ""

#: minarca_client/core/exceptions.py:82
#, fuzzy, python-format
msgid "Destination `%s` already exists."
msgstr "Der Repository-Name existiert bereits"

#: minarca_client/core/exceptions.py:92
msgid ""
"These settings conflict with an existing backup and therefore cannot be "
"created."
msgstr ""

#: minarca_client/core/exceptions.py:93
msgid ""
"It is not possible to create two backups with the same destination "
"settings. These will conflict during backup. Be sure to define a "
"different destination for this backup."
msgstr ""

#: minarca_client/core/exceptions.py:108
#, python-format
msgid ""
"your file specification [%s] doesn't match any of the base directories of"
" your system"
msgstr ""
"Ihre Dateiangabe [%s] entspricht keinem der Basisverzeichnisse Ihres "
"Systems"

#: minarca_client/core/exceptions.py:118
#, python-format
msgid "process terminated with an exception. Check logs for more details: %s"
msgstr ""
"Backup-Prozess durch eine Ausnahme beendet, überprüfen Sie die Protokolle"
" für weitere Details: %s"

#: minarca_client/core/exceptions.py:127
#, fuzzy, python-format
msgid "process returned a non-zero exit status (%s). Check logs for more details"
msgstr ""
"Backup-Prozess lieferte nicht-null Exit-Status, überprüfen Sie die "
"Protokolle für weitere Details"

#: minarca_client/core/exceptions.py:135
#: minarca_client/core/tests/test_instance.py:632
msgid "No files included in backup. Check configuration."
msgstr ""

#: minarca_client/core/exceptions.py:143
msgid "cannot stop process when it's not running."
msgstr "Prozess kann nicht gestoppt werden, wenn er nicht läuft"

#: minarca_client/core/exceptions.py:151
msgid "cannot start process when it's already running."
msgstr "Prozess kann nicht gestartet werden, wenn er bereits läuft"

#: minarca_client/core/exceptions.py:159
msgid "not configured, use `minarca configure` to configure remote host"
msgstr ""
"nicht konfiguriert, verwenden Sie `minarca configure`, um Remote-Host zu "
"konfigurieren"

#: minarca_client/core/exceptions.py:167
msgid "backup not yet scheduled to run. You may force execution using `--force`"
msgstr ""
"Backup noch nicht geplant, Sie können die Ausführung mit `--force` "
"erzwingen"

#: minarca_client/core/exceptions.py:176
#, fuzzy, python-format
msgid "Cannot establish connection to remote server."
msgstr "Konnektivität mit Remote-Server konnte nicht hergestellt werden: %s"

#: minarca_client/core/exceptions.py:178
#, python-format
msgid ""
"Your computer cannot establish a connection to the remote server. Make "
"sure your Internet connection is working and that the following URL is "
"accessible with a Web browser: %s"
msgstr ""
"Ihr Computer kann keine Verbindung zum Remote-Server herstellen. Stellen "
"Sie sicher, dass Ihre Internetverbindung funktioniert und dass auf die "
"folgende URL mit einem Webbrowser zugegriffen werden kann: %s"

#: minarca_client/core/exceptions.py:191
msgid "Invalid remote server URL!"
msgstr "Ungültige Remote-Server-URL!"

#: minarca_client/core/exceptions.py:192
msgid ""
"The remote server URL you entered for the connection is not valid. Check "
"that you have entered the correct value. The URL must begin with "
"`http://` or `https://` followed by a domain name."
msgstr ""
"Die eingegebene Remote-Server-URL für die Verbindung ist ungültig. "
"Überprüfen Sie, ob Sie den korrekten Wert eingegeben haben. Die URL muss "
"mit `http://` oder `https://` beginnen, gefolgt von einem Domain-Namen."

#: minarca_client/core/exceptions.py:204
msgid "Invalid username or password"
msgstr "Ungültiger Benutzername oder Passwort"

#: minarca_client/core/exceptions.py:205
#, fuzzy, python-format
msgid ""
"The username or password you entered to connect to the remote server is "
"not valid. If you have enabled multi-factor authentication, you need to "
"use an access token."
msgstr ""
"Der zum Verbinden mit dem Remote-Server eingegebene Benutzername oder "
"Passwort ist ungültig.\n"
"\n"
"Details: %s"

#: minarca_client/core/exceptions.py:220
msgid "The remote server returned an error. You may try again later."
msgstr ""
"Der Remote-Server hat einen Fehler zurückgegeben. Sie können es später "
"noch einmal versuchen."

#: minarca_client/core/exceptions.py:229
msgid ""
"Unable to connect to the remote server. The problem may be with the "
"remote server. If the problem persists, contact your system administrator"
" to check the SSH server configuration and a possible firewall blocking "
"the connection."
msgstr ""
"Verbindung zum Remote-Server nicht möglich. Das Problem liegt "
"möglicherweise beim Remote-Server. Wenn das Problem weiter besteht, "
"kontaktieren Sie Ihren Systemadministrator, um die SSH-"
"Serverkonfiguration und eine mögliche Firewall zu überprüfen, die die "
"Verbindung blockiert."

#: minarca_client/core/exceptions.py:244
#, fuzzy
msgid ""
"The connection to the remote server failed because our identity was "
"refused. The problem may lie with the remote server. If the problem "
"persists, contact your system administrator to check your SSH identity."
msgstr ""
"Backup fehlgeschlagen, da unsere Identität vom Remote-Server abgelehnt "
"wurde. Das Problem liegt möglicherweise beim Remote-Server. Wenn das "
"Problem weiter besteht, kontaktieren Sie Ihren Systemadministrator, um "
"Ihre SSH-Identität zu überprüfen."

#: minarca_client/core/exceptions.py:258
#, fuzzy
msgid ""
"The connection to the remote server cannot be established securely "
"because the server's identity has changed. If the problem persists, "
"contact your system administrator to verify the server's identity."
msgstr ""
"Backup fehlgeschlagen aufgrund einer unbekannten Remote Server Identität."
" Wenn das Problem weiterbesteht, kontaktieren Sie Ihren "
"Systemadministrator, um die Serveridentität zu überprüfen."

#: minarca_client/core/exceptions.py:272
msgid ""
"Backup failed due to disk quota exceeded. Please free up disk space to "
"ensure successful backup."
msgstr ""
"Backup fehlgeschlagen, da das Plattenkontingent überschritten wurde. "
"Bitte machen Sie Plattenplatz frei, um ein erfolgreiches Backup "
"sicherzustellen."

#: minarca_client/core/exceptions.py:284
msgid ""
"Backup failed due to disk being full. Please clear space on the disk to "
"proceed with the backup."
msgstr ""
"Backup fehlgeschlagen, da die Festplatte voll ist. Bitte machen Sie Platz"
" auf der Festplatte, um mit dem Backup fortzufahren."

#: minarca_client/core/exceptions.py:296
msgid ""
"The connection to the remote server has failed due to an unresolvable "
"host name. Please check your network connection and ensure that the host "
"name is still valid. If the problem persists, contact your system "
"administrator to check the host name."
msgstr ""

#: minarca_client/core/exceptions.py:310
#, fuzzy
msgid ""
"The connection to the remote server has failed due to an unsupported "
"version of the Minarca agent on the remote server. Consider updating your"
" agent or server."
msgstr ""
"Backup fehlgeschlagen aufgrund einer nicht unterstützten Minarca Agent "
"Version auf dem Remote Server. Erwägen Sie ein Upgrade Ihres Agents oder "
"Ihres Servers."

#: minarca_client/core/exceptions.py:320
msgid "The path you are trying to restore from backup does not exist."
msgstr ""
"Der Pfad, den Sie aus dem Backup wiederherstellen möchten, existiert "
"nicht."

#: minarca_client/core/exceptions.py:328
msgid "Another backup session is currently in progress on the remote server."
msgstr "Eine andere Backup-Sitzung läuft derzeit auf dem Remote-Server."

#: minarca_client/core/exceptions.py:336
msgid ""
"An internal error was raised by an unknown operation sent to the "
"background process."
msgstr ""

#: minarca_client/core/exceptions.py:348
#, fuzzy
msgid "Backup Destination Occupied"
msgstr "Backup wurde unterbrochen"

#: minarca_client/core/exceptions.py:349
msgid ""
"Unable to proceed with the selected destination as it contains existing "
"data. If you intend to use this location, kindly empty the directory of "
"any files and folders."
msgstr ""

#: minarca_client/core/exceptions.py:359
msgid "Destination Not Suitable"
msgstr ""

#: minarca_client/core/exceptions.py:360
msgid ""
"Unable to proceed with the selected destination as it cannot be "
"initialized. Make sure the external device is connected and operational."
msgstr ""

#: minarca_client/core/exceptions.py:370
msgid ""
"Backup Destination Not Found. Please ensure that your external disk or "
"network share is properly connected and accessible."
msgstr ""

#: minarca_client/core/exceptions.py:376
msgid ""
"Backup unsuccessful due to a copy operation encountering an issue, "
"potentially because the device is disconnected. Ensure your device is "
"properly connected."
msgstr ""

#: minarca_client/core/exceptions.py:390
msgid "Repository cannot be found on remote server"
msgstr ""

#: minarca_client/core/exceptions.py:395
#, python-format
msgid "Repository `%s` cannot be found on remote server"
msgstr ""

#: minarca_client/core/exceptions.py:411
msgid ""
"Repository name must contain only letters, numbers, dashes (-), and dots "
"(.)"
msgstr ""

#: minarca_client/core/latest.py:33
msgid "https://minarca.org/download/"
msgstr "https://minarca.org/download/"

#: minarca_client/core/pattern.py:87
msgid "User's Documents"
msgstr "Benutzerdokumente"

#: minarca_client/core/pattern.py:89
msgid "Minarca Config"
msgstr "Minarca Konfiguration"

#: minarca_client/core/pattern.py:96 minarca_client/core/pattern.py:155
#: minarca_client/core/pattern.py:176
msgid "Firefox Bookmark"
msgstr ""

#: minarca_client/core/pattern.py:103 minarca_client/core/pattern.py:162
#: minarca_client/core/pattern.py:177
msgid "Chrome Bookmark"
msgstr ""

#: minarca_client/core/pattern.py:110
msgid "Outlook Offline Data"
msgstr ""

#: minarca_client/core/pattern.py:117
msgid "Outlook Address Books"
msgstr ""

#: minarca_client/core/pattern.py:122
msgid "Thumbnails cache"
msgstr "Thumbnail-Cache"

#: minarca_client/core/pattern.py:123
msgid "Arrangement of a Windows folder"
msgstr "Anordnung eines Windows-Ordners"

#: minarca_client/core/pattern.py:124
msgid "Swap System File"
msgstr "Austauschsystemdatei"

#: minarca_client/core/pattern.py:125
msgid "Page System File"
msgstr "Seitensystemdatei"

#: minarca_client/core/pattern.py:126
msgid "Hibernation System File"
msgstr "Ruhezustands-Systemdatei"

#: minarca_client/core/pattern.py:127
msgid "System Volume Information"
msgstr "Systemvolumeinformation"

#: minarca_client/core/pattern.py:128
msgid "System Recovery"
msgstr "Systemwiederherstellung"

#: minarca_client/core/pattern.py:129
msgid "Recycle bin"
msgstr "Papierkorb"

#: minarca_client/core/pattern.py:130 minarca_client/core/pattern.py:183
msgid "Temporary Folder"
msgstr "Temporärer Ordner"

#: minarca_client/core/pattern.py:131
msgid "AutoCAD backup files"
msgstr "AutoCAD Sicherungsdateien"

#: minarca_client/core/pattern.py:132
msgid "Office temporary files"
msgstr "Office temporäre Dateien"

#: minarca_client/core/pattern.py:133
msgid "Outlook IMAP temporary files"
msgstr "Outlook IMAP temporäre Dateien"

#: minarca_client/core/pattern.py:134
msgid "Outlook POP temporary files"
msgstr "Outlook POP temporäre Dateien"

#: minarca_client/core/pattern.py:135
#, fuzzy
msgid "Dynacom Backup file"
msgstr "AutoCAD Sicherungsdateien"

#: minarca_client/core/pattern.py:136
#, fuzzy
msgid "Google Drive temporary upload files"
msgstr "Office temporäre Dateien"

#: minarca_client/core/pattern.py:137
#, fuzzy
msgid "Gogle Drive temporoary download files"
msgstr "Office temporäre Dateien"

#: minarca_client/core/pattern.py:142 minarca_client/core/pattern.py:171
msgid "OneDrive GUID File"
msgstr ""

#: minarca_client/core/pattern.py:145
msgid "Google Drive Shortcut Metadata"
msgstr ""

#: minarca_client/core/pattern.py:146
msgid "Google Drive Revision History"
msgstr ""

#: minarca_client/core/pattern.py:147
msgid "Google Drive Encrypted"
msgstr ""

#: minarca_client/core/pattern.py:167
msgid "Desktop Services Store"
msgstr "Desktop Dienste Speicher"

#: minarca_client/core/pattern.py:180
msgid "dev filesystem"
msgstr "dev Dateisystem"

#: minarca_client/core/pattern.py:181
msgid "proc filesystem"
msgstr "proc Dateisystem"

#: minarca_client/core/pattern.py:182
msgid "sys filesystem"
msgstr "sys Dateisystem"

#: minarca_client/core/pattern.py:184
msgid "Volatile program files"
msgstr "Flüchtige Programmdateien"

#: minarca_client/core/pattern.py:185
msgid "Mounted filesystems"
msgstr "Eingehängte Dateisysteme"

#: minarca_client/core/pattern.py:186
msgid "External media"
msgstr "Externe Medien"

#: minarca_client/core/pattern.py:187
msgid "Ext4 Lost and Found"
msgstr "Ext4 Verloren und Gefunden"

#: minarca_client/core/pattern.py:188
msgid "Hidden temporary files"
msgstr "Versteckte temporäre Dateien"

#: minarca_client/core/pattern.py:189
msgid "Vim temporary files"
msgstr "Vim temporäre Dateien"

#: minarca_client/core/scheduler.py:20
msgid "Minarca Backup"
msgstr "Minarca Backup"

#: minarca_client/core/scheduler.py:73
msgid ""
"Keeps your Minarca Backup Software running. If this task is disabled or "
"stopped, your Minarca backup will stop working. This task gets created "
"when linking Minarca with a central backup server. When installing "
"Minarca on a Windows Server, it's preferable to change the settings of "
"this task and select 'Run whether user is logged on or not' to make sure "
"the backup is running even when nobody is using the server."
msgstr ""
"Hält Ihre Minarca Backup Software am Laufen. Wenn diese Aufgabe "
"deaktiviert oder angehalten wird, wird Ihr Minarca Backup nicht mehr "
"funktionieren. Diese Aufgabe wird erstellt, wenn Minarca mit einem "
"zentralen Backup-Server verknüpft wird. Bei der Installation von Minarca "
"auf einem Windows Server ist es ratsam, die Einstellungen dieser Aufgabe "
"zu ändern und 'Ausführen, egal ob Benutzer angemeldet ist oder nicht' "
"auszuwählen, um sicherzustellen, dass das Backup ausgeführt wird, auch "
"wenn niemand den Server verwendet."

#: minarca_client/core/scheduler.py:102
msgid ""
"A problem prevents the scheduling of backup jobs. Try running the "
"application with Administrator rights."
msgstr ""

#: minarca_client/core/scheduler.py:109
msgid ""
"The user account is unknown or the password is incorrect. Be sure to "
"enter your Windows credentials."
msgstr ""

#: minarca_client/core/status.py:152
#, fuzzy
msgid "Your backup is outdated"
msgstr "Backup ist veraltet"

#: minarca_client/core/status.py:153
#, python-format
msgid ""
"Your backup %s is outdated by over %s days. Please plug in your local "
"device and run the backup."
msgstr ""

#: minarca_client/core/notification/_notification_win.py:127
#, fuzzy
msgid "Show details"
msgstr "Details: "

#: minarca_client/dialogs/_dialogs_cocoa.py:72
#, fuzzy
msgid "Yes"
msgstr "ja"

#: minarca_client/dialogs/_dialogs_cocoa.py:72
msgid "No"
msgstr ""

#: minarca_client/ui/about_menu.py:20
#: minarca_client/ui/backup_connection_local.py:27
msgid "Browse"
msgstr ""

#: minarca_client/ui/about_menu.py:20
msgid "Settings"
msgstr "Einstellungen"

#: minarca_client/ui/about_menu.py:20
#, fuzzy
msgid "Get Help"
msgstr "Hilfe"

#: minarca_client/ui/about_menu.py:20
msgid "Help"
msgstr "Hilfe"

#: minarca_client/ui/about_menu.py:20
msgid "Website"
msgstr ""

#: minarca_client/ui/about_menu.py:20
#, fuzzy
msgid "Minarca Agent"
msgstr "Minarca Konfiguration"

#: minarca_client/ui/about_menu.py:20
#, python-format
msgid "Version %s"
msgstr ""

#: minarca_client/ui/about_menu.py:20
#, fuzzy
msgid "Update now"
msgstr "Updates"

#: minarca_client/ui/about_menu.py:20
msgid "Copyright © 2024 IKUS Software"
msgstr ""

#: minarca_client/ui/about_menu.py:128 minarca_client/ui/about_menu.py:130
#: minarca_client/ui/backup_connection_local.py:237
#, python-format
msgid "%s on %s"
msgstr ""

#: minarca_client/ui/about_menu.py:228
#, fuzzy
msgid "Checking for updates..."
msgstr "Suche nach Updates"

#: minarca_client/ui/about_menu.py:230
msgid "Unable to verify update availability at this time."
msgstr ""

#: minarca_client/ui/about_menu.py:232
#, fuzzy, python-format
msgid "New version %s available"
msgstr "neue Version %s verfügbar"

#: minarca_client/ui/about_menu.py:234
msgid "Current version is up-to-date"
msgstr "Aktuelle Version ist auf dem neuesten Stand"

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:10
#: minarca_client/ui/side_pannel.py:102
#, fuzzy
msgid "Online backup"
msgstr "Minarca Backup"

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_create.py:10
#: minarca_client/ui/side_pannel.py:109
#, fuzzy
msgid "Local backup"
msgstr "Datensicherung"

#: minarca_client/ui/backup_card.py:21
#, fuzzy
msgid "Paused"
msgstr "Anhalten"

#: minarca_client/ui/backup_card.py:21
msgid "Active"
msgstr ""

#: minarca_client/ui/backup_card.py:21 minarca_client/ui/backup_settings.py:22
#, fuzzy
msgid "Backup configuration"
msgstr "Bestätigung zum Anhalten des Backup-Jobs"

#: minarca_client/ui/backup_card.py:21
#: minarca_client/ui/backup_restore_custom.py:30
#: minarca_client/ui/backup_restore_full.py:30
msgid "File selection"
msgstr ""

#: minarca_client/ui/backup_card.py:21
#, fuzzy
msgid "Restore backup"
msgstr "Backup starten"

#: minarca_client/ui/backup_card.py:288
msgid "Calculating disk usage"
msgstr ""

#: minarca_client/ui/backup_card.py:290
msgid "Cannot determine disk usage"
msgstr ""

#: minarca_client/ui/backup_card.py:291
#, python-format
msgid "Used space %s"
msgstr ""

#: minarca_client/ui/backup_card.py:299
#, python-format
msgid "Total space %s"
msgstr ""

#: minarca_client/ui/backup_card.py:304
msgid "Stopping..."
msgstr ""

#: minarca_client/ui/backup_card.py:304
#, fuzzy
msgid "Starting..."
msgstr "Einstellungen"

#: minarca_client/ui/backup_card.py:309
#, fuzzy
msgid "Stop Restore"
msgstr "Wiederherstellen"

#: minarca_client/ui/backup_card.py:310
#, fuzzy
msgid "Stop Backup"
msgstr "Backup stoppen"

#: minarca_client/ui/backup_card.py:312
#, fuzzy
msgid "Start Backup now"
msgstr "Backup starten"

#: minarca_client/ui/backup_card.py:320 minarca_client/ui/backup_logs.py:268
msgid "No backup yet"
msgstr "Noch kein Backup"

#: minarca_client/ui/backup_card.py:324
#, fuzzy
msgid "Backup in progress..."
msgstr "Backup läuft"

#: minarca_client/ui/backup_card.py:325 minarca_client/ui/backup_logs.py:272
#, fuzzy, python-format
msgid "Last backup: %s"
msgstr "Letztes erfolgreiches Backup: %s"

#: minarca_client/ui/backup_card.py:328
#, fuzzy
msgid "Restore in progress..."
msgstr "Wiederherstellung läuft"

#: minarca_client/ui/backup_card.py:329 minarca_client/ui/backup_logs.py:274
#, fuzzy, python-format
msgid "Last restore: %s"
msgstr "Partielle Wiederherstellung"

#: minarca_client/ui/backup_card.py:336
#: minarca_client/ui/backup_connection_remote.py:21
#, fuzzy
msgid "Server connection"
msgstr "Verbinden"

#: minarca_client/ui/backup_card.py:336
#, fuzzy
msgid "Local connection"
msgstr "Verbinden"

#: minarca_client/ui/backup_card.py:380
msgid "Pause Backup Job Confirmation"
msgstr "Bestätigung zum Anhalten des Backup-Jobs"

#: minarca_client/ui/backup_card.py:381
msgid "Are you sure you want to pause the backup job?"
msgstr "Sind Sie sicher, dass Sie den Backup-Job anhalten möchten?"

#: minarca_client/ui/backup_card.py:382
#, fuzzy
msgid ""
"Pausing the backup job will temporarily suspend the ongoing backup "
"process for the next 24 hours. This action may affect the availability of"
" recent data restore points and introduce delays in the backup schedule. "
"Please confirm your intention before proceeding."
msgstr ""
"Durch das Anhalten des Backup-Jobs wird der laufende Backup-Prozess für "
"die nächsten 12 Stunden ausgesetzt. Dies kann die Verfügbarkeit aktueller"
" Wiederherstellungspunkte beeinträchtigen und Verzögerungen im Backup-"
"Zeitplan verursachen. Bitte bestätigen Sie Ihre Absicht, bevor Sie "
"fortfahren."

#: minarca_client/ui/backup_card.py:401
msgid "Start Backup"
msgstr "Backup starten"

#: minarca_client/ui/backup_card.py:402
msgid "A problem occurred when trying to start the backup process."
msgstr "Beim Versuch, den Backup-Prozess zu starten, ist ein Problem aufgetreten."

#: minarca_client/ui/backup_card.py:403
msgid ""
"This usually indicate a problem with the installation. Try re-installing "
"Minarca Backup."
msgstr ""
"Dies deutet in der Regel auf ein Problem mit der Installation hin. "
"Versuchen Sie, Minarca Backup neu zu installieren."

#: minarca_client/ui/backup_card.py:417 minarca_client/ui/backup_logs.py:328
msgid "Stop process"
msgstr "Prozess stoppen"

#: minarca_client/ui/backup_card.py:418 minarca_client/ui/backup_logs.py:329
msgid "A problem occurred when trying to stop the process."
msgstr "Beim Versuch, den Prozess zu stoppen, ist ein Problem aufgetreten."

#: minarca_client/ui/backup_connection_local.py:27
msgid "Select a location to be used for backing up your data."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid "Target location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid "Edit target location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#, fuzzy
msgid "Backup name"
msgstr "Backup fehlgeschlagen"

#: minarca_client/ui/backup_connection_local.py:27
msgid "Refresh"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
msgid ""
"No external drive has been detected for data backup. Plug in your "
"external drive and click on the refresh button to update this list. If "
"your device is not on the list, check its connectivity and make sure it's"
" switched on."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_create.py:10 minarca_client/ui/backup_logs.py:24
#: minarca_client/ui/backup_restore.py:16
#: minarca_client/ui/backup_restore_custom.py:30
#: minarca_client/ui/backup_restore_date.py:24
#: minarca_client/ui/backup_restore_full.py:30
#: minarca_client/ui/backup_settings.py:22
msgid "Back"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_settings.py:22
msgid "Cancel"
msgstr "Abbrechen"

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_restore_date.py:24
#: minarca_client/ui/backup_settings.py:22
msgid "Next"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_settings.py:22
msgid "Save"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:27
#: minarca_client/ui/backup_connection_remote.py:21
#: minarca_client/ui/backup_settings.py:22
msgid "Delete backup settings"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:250
#, fuzzy, python-format
msgid "%s Drive with %s available space"
msgstr "neue Version %s verfügbar"

#: minarca_client/ui/backup_connection_local.py:252
#, python-format
msgid " • Format %s"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:261
msgid ""
"Detected as a fixed device. Prefer using removable or network storage to "
"avoid data loss."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:263
msgid ""
"Ensure this network location is configured to automatically reconnect to "
"avoid data loss."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:265
msgid "FAT32 file system is not recommended for backup."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:267
msgid "Samba share over Gnome Virtual File system is not compatible."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:269
msgid ""
"NTFS isn't recommended on Linux due to remount issues after improper "
"unmounting."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:272
msgid "Available disk space at this location is limited."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:400
msgid "You don't have permissions to write at this location."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:406
#, fuzzy
msgid "Destination already exists"
msgstr "Der Repository-Name existiert bereits"

#: minarca_client/ui/backup_connection_local.py:407
#: minarca_client/ui/backup_connection_remote.py:286
msgid "Do you want to replace the existing repository?"
msgstr "Möchten Sie das bestehende Repository ersetzen?"

#: minarca_client/ui/backup_connection_local.py:408
#, fuzzy
msgid ""
"The selected destination already exists at this location. If you continue"
" with this repository, you will replace its content using this computer. "
msgstr ""
"Der eingegebene Repository-Name existiert bereits auf dem Remote-Server. "
"Wenn Sie mit diesem Repository fortfahren, wird der Inhalt durch diesen "
"Computer ersetzt. Andernfalls müssen Sie einen anderen Repository-Namen "
"eingeben."

#: minarca_client/ui/backup_connection_local.py:422
#, fuzzy
msgid "Unknown problem occurred when trying to configure the destination."
msgstr "Beim Versuch, den Prozess zu stoppen, ist ein Problem aufgetreten."

#: minarca_client/ui/backup_connection_local.py:450
msgid "Please wait. Scanning for removable disks..."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:461
msgid ""
"Please choose an external device or network share as your backup "
"destination."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:472
#: minarca_client/ui/backup_connection_local.py:473
msgid "Unable to retrieve information from selected location"
msgstr ""

#: minarca_client/ui/backup_connection_local.py:474
msgid ""
"Unable to obtain detailed information on the selected location. Please "
"ensure that this location is accessible and valid. If the problem "
"persists, consult the application log with your administrator."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:498
msgid "Please wait. Initializing backup..."
msgstr ""

#: minarca_client/ui/backup_connection_local.py:510
#: minarca_client/ui/backup_connection_remote.py:253
#: minarca_client/ui/backup_settings.py:424
msgid "Are you sure?"
msgstr "Sind Sie sicher?"

#: minarca_client/ui/backup_connection_local.py:511
#, fuzzy
msgid "Are you sure you want to delete this backup configuration?"
msgstr "Sind Sie sicher, dass Sie den Backup-Job anhalten möchten?"

#: minarca_client/ui/backup_connection_local.py:512
#, fuzzy
msgid ""
"If you delete this backup configuration, this Minarca agent will erase "
"its identity and will no longer run backup on schedule."
msgstr ""
"Wenn Sie diesen Computer trennen, wird dieser Minarca-Agent seine "
"Identität löschen und keine planmäßigen Backups mehr ausführen."

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Provide your login details to configure remote backup."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
#, fuzzy
msgid "Edit server connection"
msgstr "Trennen"

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Address (IP or domain)"
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Username"
msgstr "Benutzername"

#: minarca_client/ui/backup_connection_remote.py:21
msgid "Password"
msgstr "Passwort"

#: minarca_client/ui/backup_connection_remote.py:243
msgid "Please wait. Initializing backup on remote server..."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:254
#: minarca_client/ui/backup_settings.py:425
#, fuzzy
msgid "Are you sure you want to forget these backup settings?"
msgstr "Sind Sie sicher, dass Sie den Backup-Job anhalten möchten?"

#: minarca_client/ui/backup_connection_remote.py:255
#: minarca_client/ui/backup_settings.py:426
msgid "If you forget these settings, the backup will no longer run on schedule."
msgstr ""

#: minarca_client/ui/backup_connection_remote.py:285
msgid "Repository name already exists"
msgstr "Der Repository-Name existiert bereits"

#: minarca_client/ui/backup_connection_remote.py:287
msgid ""
"The repository name you have entered already exists on the remote server."
" If you continue with this repository, you will replace its content using"
" this computer. Otherwise, you must enter a different repository name."
msgstr ""
"Der eingegebene Repository-Name existiert bereits auf dem Remote-Server. "
"Wenn Sie mit diesem Repository fortfahren, wird der Inhalt durch diesen "
"Computer ersetzt. Andernfalls müssen Sie einen anderen Repository-Namen "
"eingeben."

#: minarca_client/ui/backup_connection_remote.py:302
#, fuzzy, python-format
msgid "Failed to establish connectivity with remote server."
msgstr "Konnektivität mit Remote-Server konnte nicht hergestellt werden: %s"

#: minarca_client/ui/backup_connection_remote.py:306
#, fuzzy
msgid "Unknown problem occured when connecting to the remote server."
msgstr "Unbekanntes Problem beim Verbinden mit dem Remote-Server"

#: minarca_client/ui/backup_connection_remote.py:307
#, python-format
msgid ""
"An error occurred during the connection to Minarca server.\n"
"\n"
"Details: %s"
msgstr ""
"Während der Verbindung zum Minarca-Server ist ein Fehler aufgetreten.\n"
"\n"
"Details: %s"

#: minarca_client/ui/backup_create.py:10
#, fuzzy
msgid "Create a backup"
msgstr "Datensicherung"

#: minarca_client/ui/backup_create.py:10
msgid "Dedicated centralized server"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "Accessible anywhere"
msgstr ""

#: minarca_client/ui/backup_create.py:10
#, fuzzy
msgid "Remote backup"
msgstr "Datensicherung"

#: minarca_client/ui/backup_create.py:10
msgid "Setup"
msgstr ""

#: minarca_client/ui/backup_create.py:10
msgid "External disk or network share"
msgstr ""

#: minarca_client/ui/backup_create.py:10
#, fuzzy
msgid "Offline accessibility"
msgstr "Erfolgreich verknüpft"

#: minarca_client/ui/backup_create.py:10
#, fuzzy
msgid "Standalone backup"
msgstr "Backup starten"

#: minarca_client/ui/backup_logs.py:24
msgid "Get detailed information about your last backup or restore operation."
msgstr ""

#: minarca_client/ui/backup_logs.py:24
msgid "Open file in text editor..."
msgstr ""

#: minarca_client/ui/backup_logs.py:24
msgid "Scroll to bottom"
msgstr ""

#: minarca_client/ui/backup_logs.py:244
#, fuzzy
msgid "Restore logs"
msgstr "Wiederherstellen"

#: minarca_client/ui/backup_logs.py:245
#, fuzzy
msgid "Backup logs"
msgstr "Backup läuft"

#: minarca_client/ui/backup_logs.py:252
#, fuzzy, python-format
msgid "Backup in progress for %s..."
msgstr "Backup läuft"

#: minarca_client/ui/backup_logs.py:254
#, fuzzy, python-format
msgid "Data restoration in progress for %s..."
msgstr "Wiederherstellung läuft"

#: minarca_client/ui/backup_logs.py:289
#, python-format
msgid "The last backup ended with the following error: %s"
msgstr ""

#: minarca_client/ui/backup_logs.py:291
#, python-format
msgid "The last restoration ended with the following error: %s"
msgstr ""

#: minarca_client/ui/backup_logs.py:314
#, fuzzy
msgid "Confirmation Required"
msgstr "Abruf der Minarca-Konfiguration"

#: minarca_client/ui/backup_logs.py:315
#, fuzzy
msgid "Are you sure you want to stop the ongoing backup/restore process?"
msgstr "Sind Sie sicher, dass Sie den Backup-Job anhalten möchten?"

#: minarca_client/ui/backup_logs.py:316
msgid ""
"Your data may be incomplete or corrupted if the operation is terminated "
"prematurely. Please confirm your decision before proceeding."
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "Select the files and folders you want to back up."
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
msgid "File Selection"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
#, fuzzy
msgid "Files included"
msgstr "Enthalten"

#: minarca_client/ui/backup_patterns.py:23
#, fuzzy
msgid "Files excluded"
msgstr "Ausgeschlossen"

#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_patterns.py:266
msgid "Add file"
msgstr "Datei hinzufügen"

#: minarca_client/ui/backup_patterns.py:23
#, fuzzy
msgid "Exclude file"
msgstr "Ausgeschlossen"

#: minarca_client/ui/backup_patterns.py:23
#: minarca_client/ui/backup_patterns.py:255
msgid "Add folder"
msgstr "Ordner hinzufügen"

#: minarca_client/ui/backup_patterns.py:23
#, fuzzy
msgid "Exclude folder"
msgstr "Ausgeschlossen"

#: minarca_client/ui/backup_patterns.py:23
msgid "File extention (e.g.: *.txt)"
msgstr ""

#: minarca_client/ui/backup_patterns.py:23
#, fuzzy
msgid "Exclude"
msgstr "Ausgeschlossen"

#: minarca_client/ui/backup_patterns.py:23
#, fuzzy
msgid "Restore to default"
msgstr "Standard wiederherstellen"

#: minarca_client/ui/backup_restore.py:16
msgid ""
"Choose between restoring all files in place or selecting specific files "
"for restoration."
msgstr ""

#: minarca_client/ui/backup_restore.py:16
#, fuzzy
msgid "Restore Options"
msgstr "Wiederherstellung abgeschlossen"

#: minarca_client/ui/backup_restore.py:16
#, fuzzy
msgid "Custom restore"
msgstr "Komplette Wiederherstellung"

#: minarca_client/ui/backup_restore.py:16
#, fuzzy
msgid "Select file(s) to restore"
msgstr "Dateien für die vollständige Wiederherstellung auswählen"

#: minarca_client/ui/backup_restore.py:16
#, fuzzy
msgid "Select destination"
msgstr "Dateien auswählen"

#: minarca_client/ui/backup_restore.py:16
msgid "Ideal for quick recovery"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
#, fuzzy
msgid "Full restore"
msgstr "Komplette Wiederherstellung"

#: minarca_client/ui/backup_restore.py:16
#, fuzzy
msgid "Restore all files"
msgstr "Wiederherstellung fehlgeschlagen"

#: minarca_client/ui/backup_restore.py:16
msgid "Replace existing files"
msgstr ""

#: minarca_client/ui/backup_restore.py:16
msgid "Ideal for hardware failure"
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:30
msgid ""
"When you perform a custom restore, the selected item is restored to a "
"different location selected by you."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:30
msgid "Search for files or folders..."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:30
#, fuzzy
msgid "Restore..."
msgstr "Wiederherstellen"

#: minarca_client/ui/backup_restore_custom.py:201
#: minarca_client/ui/backup_restore_full.py:173
msgid "Please wait. Getting file list..."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:218
#: minarca_client/ui/backup_restore_full.py:204
msgid "Failed to retrieve available files."
msgstr ""

#: minarca_client/ui/backup_restore_custom.py:222
#: minarca_client/ui/backup_restore_full.py:208
#, fuzzy
msgid "Unknown problem occurred when collecting file list."
msgstr "Unbekanntes Problem beim Verbinden mit dem Remote-Server"

#: minarca_client/ui/backup_restore_custom.py:266
#, fuzzy
msgid "Select a folder where to restore data."
msgstr "Dateien und Ordner, die wiederhergestellt werden sollen"

#: minarca_client/ui/backup_restore_date.py:24
msgid "Choose the point in time of data to be restored."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:24
#, fuzzy
msgid "Select date & Time"
msgstr "Dateien auswählen"

#: minarca_client/ui/backup_restore_date.py:173
msgid "Please wait. Loading backup dates..."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:181
msgid "Failed to retrieve available backup dates."
msgstr ""

#: minarca_client/ui/backup_restore_date.py:185
#, fuzzy
msgid "Unknown problem occurred when collecting backup dates."
msgstr "Beim Versuch, den Backup-Prozess zu starten, ist ein Problem aufgetreten."

#: minarca_client/ui/backup_restore_full.py:30
msgid ""
"When you perform a full restore, the selected items will be restored to "
"their original location on your device."
msgstr ""

#: minarca_client/ui/backup_restore_full.py:30
msgid ""
"I understand that full restore replaces existing files on my device and "
"may result in data loss if the destination is not empty."
msgstr ""

#: minarca_client/ui/backup_restore_full.py:30
msgid "Restore"
msgstr "Wiederherstellen"

#: minarca_client/ui/backup_restore_full.py:249
#, fuzzy
msgid "Confirm Full Restore"
msgstr "Komplette Wiederherstellung"

#: minarca_client/ui/backup_restore_full.py:250
#, fuzzy
msgid "Are you sure you want to run a full restoration?"
msgstr "Sind Sie sicher, dass Sie den Backup-Job anhalten möchten?"

#: minarca_client/ui/backup_restore_full.py:251
msgid ""
"This action will overwrite all existing files selected with the previous "
"version present in the backup. This action is irreversible and may result"
" in data loss."
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Configure your backup settings for personalized data protection."
msgstr ""

#: minarca_client/ui/backup_settings.py:22
#, fuzzy
msgid "Backup frequency"
msgstr "Häufigkeit"

#: minarca_client/ui/backup_settings.py:22
#, fuzzy
msgid "Run whether the user's session is open or not"
msgstr "Ausführen, egal ob Benutzer angemeldet ist oder nicht"

#: minarca_client/ui/backup_settings.py:22
msgid "Excluded Days of the Week"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
#, fuzzy
msgid "Monday"
msgstr "Ändern"

#: minarca_client/ui/backup_settings.py:22
msgid "Tuesday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Wednesday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Thrusday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Friday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
msgid "Saturday"
msgstr ""

#: minarca_client/ui/backup_settings.py:22
#, fuzzy
msgid "Sunday"
msgstr "Anhalten"

#: minarca_client/ui/backup_settings.py:22
#, fuzzy
msgid "Data Retention Duration"
msgstr "Partielle Wiederherstellung"

#: minarca_client/ui/backup_settings.py:22
msgid "Inactivity Notification Period"
msgstr ""

#: minarca_client/ui/backup_settings.py:224
msgid "Please wait. Loading backup settings..."
msgstr ""

#: minarca_client/ui/backup_settings.py:247
msgid "Hourly"
msgstr "Stündlich"

#: minarca_client/ui/backup_settings.py:247
#, fuzzy
msgid "Four times a day"
msgstr "Zweimal täglich"

#: minarca_client/ui/backup_settings.py:247
msgid "Twice a day"
msgstr "Zweimal täglich"

#: minarca_client/ui/backup_settings.py:247
msgid "Once a day"
msgstr "Einmal täglich"

#: minarca_client/ui/backup_settings.py:254
#: minarca_client/ui/backup_settings.py:273
msgid "1 day"
msgstr ""

#: minarca_client/ui/backup_settings.py:255
#: minarca_client/ui/backup_settings.py:274
msgid "2 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:256
#: minarca_client/ui/backup_settings.py:275
msgid "3 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:257
#: minarca_client/ui/backup_settings.py:276
msgid "4 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:258
#: minarca_client/ui/backup_settings.py:277
msgid "5 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:259
#: minarca_client/ui/backup_settings.py:278
msgid "6 days"
msgstr ""

#: minarca_client/ui/backup_settings.py:260
#: minarca_client/ui/backup_settings.py:279
msgid "1 week"
msgstr ""

#: minarca_client/ui/backup_settings.py:261
#: minarca_client/ui/backup_settings.py:280
msgid "2 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:262
#: minarca_client/ui/backup_settings.py:281
msgid "3 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:263
msgid "4 weeks"
msgstr ""

#: minarca_client/ui/backup_settings.py:264
#: minarca_client/ui/backup_settings.py:282
msgid "1 month"
msgstr ""

#: minarca_client/ui/backup_settings.py:272
#, fuzzy
msgid "Forever"
msgstr "Nie"

#: minarca_client/ui/backup_settings.py:283
msgid "2 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:284
msgid "3 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:285
msgid "4 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:286
msgid "5 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:287
msgid "6 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:288
msgid "7 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:289
msgid "8 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:290
msgid "9 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:291
msgid "10 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:292
msgid "11 months"
msgstr ""

#: minarca_client/ui/backup_settings.py:293
msgid "1 year"
msgstr ""

#: minarca_client/ui/backup_settings.py:294
#, fuzzy
msgid "2 years"
msgstr "ja"

#: minarca_client/ui/backup_settings.py:295
#, fuzzy
msgid "3 years"
msgstr "ja"

#: minarca_client/ui/backup_settings.py:296
#, fuzzy
msgid "4 years"
msgstr "ja"

#: minarca_client/ui/backup_settings.py:297
#, fuzzy
msgid "5 years"
msgstr "ja"

#: minarca_client/ui/backup_settings.py:317
msgid "Unable to retrieve settings from remote server."
msgstr ""

#: minarca_client/ui/backup_settings.py:318
msgid ""
"This issue may arise due to the remote server being out-of-date. You may "
"edit the settings, however, some settings will not be synchronized with "
"the remote server. If this problem persists, we recommend contacting your"
" administrator for further assistance."
msgstr ""

#: minarca_client/ui/backup_settings.py:326
#, fuzzy
msgid "Unable to retrieve configuration from remote server."
msgstr "Verbindung mit Remote-Server fehlgeschlagen"

#: minarca_client/ui/backup_settings.py:327
#, fuzzy, python-format
msgid ""
"An error occurred during the connection.\n"
"\n"
"Details: %s"
msgstr ""
"Während der Verbindung zum Minarca-Server ist ein Fehler aufgetreten.\n"
"\n"
"Details: %s"

#: minarca_client/ui/backup_settings.py:346
msgid "Please wait. Saving settings..."
msgstr ""

#: minarca_client/ui/backup_settings.py:376
#, fuzzy
msgid "Repository not found"
msgstr "Name des zu verwendenden Repositorys"

#: minarca_client/ui/backup_settings.py:377
#: minarca_client/ui/backup_settings.py:399
#, fuzzy
msgid "A problem occured while trying to save the backup settings."
msgstr "Beim Versuch, den Backup-Prozess zu starten, ist ein Problem aufgetreten."

#: minarca_client/ui/backup_settings.py:383
#, fuzzy
msgid "Authentication failed"
msgstr "Verbindung fehlgeschlagen"

#: minarca_client/ui/backup_settings.py:384
#, fuzzy
msgid ""
"Your settings could not be saved to remote server. Do you want to "
"continue ?"
msgstr ""
"Minarca-Konfiguration konnte nicht abgerufen werden. Möchten Sie "
"fortfahren?"

#: minarca_client/ui/backup_settings.py:385
msgid ""
"This issue may arise due to the remote server being out-of-date. You have"
" the option to proceed, however, some settings will not be synchronized "
"with the remote server. If this problem persists, we recommend contacting"
" your administrator for further assistance."
msgstr ""

#: minarca_client/ui/backup_settings.py:398
msgid "Save Settings timeout"
msgstr ""

#: minarca_client/ui/backup_settings.py:400
msgid ""
"The operation timeout. Check your internet connection and verify if the "
"remote server is online. If the problem persist contact your "
"administrator."
msgstr ""

#: minarca_client/ui/backup_settings.py:408
msgid "Cannot save settings"
msgstr ""

#: minarca_client/ui/backup_settings.py:409
msgid ""
"An unknown problem occured while trying to save the backup settings. If "
"the problem persist contact your administrator."
msgstr ""

#: minarca_client/ui/backup_settings.py:454
msgid "Windows Credentials"
msgstr ""

#: minarca_client/ui/backup_settings.py:454
msgid "Enter credentials for local machine:"
msgstr ""

#: minarca_client/ui/backup_settings.py:459
#, fuzzy
msgid "Cannot apply your changes."
msgstr "Der Taskplaner kann Ihre Änderungen nicht übernehmen."

#: minarca_client/ui/backup_settings.py:463
#, fuzzy
msgid "Backup Configuration"
msgstr "Bestätigung zum Anhalten des Backup-Jobs"

#: minarca_client/ui/dashboard.py:17
msgid "Dashboard"
msgstr ""

#: minarca_client/ui/dashboard.py:17
#, fuzzy
msgid "Setup backup"
msgstr "Backup starten"

#: minarca_client/ui/side_pannel.py:98
#, fuzzy
msgid "Create an online backup"
msgstr "Daten aus Backup wiederherstellen"

#: minarca_client/ui/side_pannel.py:100
#, fuzzy
msgid "Online restore"
msgstr "Komplette Wiederherstellung"

#: minarca_client/ui/side_pannel.py:105
#, fuzzy
msgid "Create a local backup"
msgstr "Daten aus Backup wiederherstellen"

#: minarca_client/ui/side_pannel.py:107
#, fuzzy
msgid "Local restore"
msgstr "Komplette Wiederherstellung"

#~ msgid "minarca is already linked, execute `minarca unlink`"
#~ msgstr "minarca ist bereits verknüpft, führen Sie `minarca unlink` aus"

#~ msgid ""
#~ "A problem prevent the automatic "
#~ "scheduling of backup jobs. As a "
#~ "result, your backup tasks cannot be "
#~ "executed as planned."
#~ msgstr ""
#~ "Ein Problem verhindert die automatische "
#~ "Planung von Backup-Jobs. Daher können"
#~ " Ihre Backup-Aufgaben nicht wie "
#~ "geplant ausgeführt werden."

#~ msgid "link this minarca backup with a minarca server"
#~ msgstr "Verknüpfen Sie dieses minarca-Backup mit einem minarca-Server"

#~ msgid "link to remote server even if the repository name already exists"
#~ msgstr ""
#~ "Verbindung mit Remote-Server herstellen, "
#~ "auch wenn der Repository-Name bereits"
#~ " existiert"

#~ msgid "unlink this minarca client from server"
#~ msgstr "Diese minarca-Clientverbindung zum Server aufheben"

#~ msgid "generating identity"
#~ msgstr "Identität wird generiert"

#~ msgid "exchanging identity with minarca server"
#~ msgstr "Identitätsaustausch mit Minarca-Server"

#~ msgid "generating new identity"
#~ msgstr "Neue Identität wird generiert"

#~ msgid "exchanging new identity with minarca server"
#~ msgstr "Austausch der neuen Identität mit Minarca-Server"

#~ msgid "executing command: %s"
#~ msgstr "Befehl wird ausgeführt: %s"

#~ msgid ""
#~ "Fail to link because repository with "
#~ "name `%s` already exists on remote "
#~ "server."
#~ msgstr ""
#~ "Fehler beim Verlinken, da das Repository"
#~ " mit dem Namen `%s` bereits auf "
#~ "dem Remote-Server existiert."

#~ msgid "include patterns are missing"
#~ msgstr "Include-Muster fehlen"

#~ msgid "cannot establish connection to `%s`, verify if the URL is valid"
#~ msgstr ""
#~ "Verbindung zu `%s` kann nicht "
#~ "hergestellt werden, überprüfen Sie, ob "
#~ "die URL gültig ist"

#~ msgid ""
#~ "the given URL `%s` is not properly"
#~ " formated, verify if the URL is "
#~ "valid. It must start with either "
#~ "https:// or http://"
#~ msgstr ""
#~ "Die angegebene URL `%s` hat kein "
#~ "gültiges Format, überprüfen Sie, ob die"
#~ " URL gültig ist. Sie muss mit "
#~ "https:// oder http:// beginnen"

#~ msgid "authentication refused, verify your username and password"
#~ msgstr ""
#~ "Authentifizierung abgelehnt, überprüfen Sie "
#~ "Ihren Benutzernamen und Ihr Passwort"

#~ msgid ""
#~ "remote server return an error, check "
#~ "remote server log with your "
#~ "administrator"
#~ msgstr ""
#~ "Der Remote-Server meldet einen Fehler,"
#~ " prüfen Sie das Remote-Server-"
#~ "Protokoll mit Ihrem Administrator"

#~ msgid ""
#~ "Backup failed due unresolvable hostname. "
#~ "Please check your network connection and"
#~ " ensure the hostname is valid."
#~ msgstr ""
#~ "Backup fehlgeschlagen aufgrund eines nicht "
#~ "auflösbaren Hostnamens. Bitte überprüfen Sie"
#~ " Ihre Netzwerkverbindung und stellen Sie"
#~ " sicher, dass der Hostname gültig "
#~ "ist."

#~ msgid "Add Folder Pattern"
#~ msgstr "Ordnermuster hinzufügen"

#~ msgid "Add custom pattern"
#~ msgstr "Benutzerdefiniertes Muster hinzufügen"

#~ msgid ""
#~ "You may provide a custom pattern to include or exclude file.\n"
#~ "Custom pattern may include wildcard `*` or `?`."
#~ msgstr ""
#~ "Sie können ein benutzerdefiniertes Muster "
#~ "zum Ein- oder Ausschließen von Dateien"
#~ " angeben.\n"
#~ "Benutzerdefinierte Muster können Platzhalter `*` oder `?` enthalten."

#~ msgid "Confirm Restore Default"
#~ msgstr "Wiederherstellung der Standardeinstellungen bestätigen"

#~ msgid ""
#~ "Are you sure you want to restore"
#~ " default list of selected file and"
#~ " folder?"
#~ msgstr ""
#~ "Möchten Sie wirklich die Standardliste "
#~ "der ausgewählten Dateien und Ordner "
#~ "wiederherstellen?"

#~ msgid ""
#~ "This action will reset the selected "
#~ "files and folders to their default "
#~ "settings. Any changes you have made "
#~ "will be lost. Please note that "
#~ "this operation cannot be undone."
#~ msgstr ""
#~ "Durch diese Aktion werden die "
#~ "ausgewählten Dateien und Ordner auf die"
#~ " Standardwerte zurückgesetzt. Alle Änderungen "
#~ "gehen verloren. Bitte beachten Sie, dass"
#~ " dieser Vorgang nicht rückgängig gemacht"
#~ " werden kann."

#~ msgid "Ignore"
#~ msgstr "Ignorieren"

#~ msgid "Operation already in Progress"
#~ msgstr "Operation bereits im Gange"

#~ msgid ""
#~ "A restore or backup operation is "
#~ "currently running. Please wait for the"
#~ " operation to complete before initiating"
#~ " a full recovery. Initiating a "
#~ "recovery while a restore or backup "
#~ "is in progress may lead to data"
#~ " inconsistencies or errors."
#~ msgstr ""
#~ "Eine Wiederherstellungs- oder Sicherungsoperation"
#~ " läuft derzeit. Bitte warten Sie, bis"
#~ " der Vorgang abgeschlossen ist, bevor "
#~ "Sie eine vollständige Wiederherstellung "
#~ "starten. Das Starten einer Wiederherstellung"
#~ " während eine Wiederherstellung oder "
#~ "Sicherung läuft, kann zu Dateninkonsistenzen"
#~ " oder Fehlern führen."

#~ msgid ""
#~ "Retrieval of Minarca configuration operation"
#~ " has encountered an error or has "
#~ "failed to locate the configuration file."
#~ " Continuing without retrieving the Minarca"
#~ " configuration require you to manually "
#~ "verify the selected files otherwise it"
#~ " may result in potential data loss"
#~ " during the restore process."
#~ msgstr ""
#~ "Beim Abrufen der Minarca-Konfiguration "
#~ "ist ein Fehler aufgetreten oder die "
#~ "Konfigurationsdatei wurde nicht gefunden. Ohne"
#~ " Abruf der Minarca-Konfiguration müssen "
#~ "Sie die ausgewählten Dateien manuell "
#~ "überprüfen, da es sonst zu potenziellem"
#~ " Datenverlust während der Wiederherstellung "
#~ "kommen kann."

#~ msgid "Task Scheduler"
#~ msgstr "Taskplaner"

#~ msgid "New version available"
#~ msgstr "Neue Version verfügbar"

#~ msgid ""
#~ "A new version of Minarca (%s) is"
#~ " available from IKUS Software. Do you"
#~ " want to upgrade your copy ?"
#~ msgstr ""
#~ "Eine neue Version von Minarca (%s) "
#~ "ist von IKUS Software verfügbar. Möchten"
#~ " Sie Ihre Kopie upgraden?"

#~ msgid ""
#~ "Minarca automatically checks for new "
#~ "updates. You can change how Minarca "
#~ "checks for updates in Minarca's "
#~ "settings."
#~ msgstr ""
#~ "Minarca sucht automatisch nach neuen "
#~ "Updates. Sie können ändern, wie Minarca"
#~ " nach Updates sucht, in den "
#~ "Minarca-Einstellungen."

#~ msgid "Are you sure you want to disconnect this Minarca agent ?"
#~ msgstr "Sind Sie sicher, dass Sie diesen Minarca-Agenten trennen möchten?"

#~ msgid "Connection Error"
#~ msgstr "Verbindungsfehler"

#~ msgid "Server Error"
#~ msgstr "Serverfehler"

#~ msgid "Welcome %s"
#~ msgstr "Willkommen %s"

#~ msgid "Backup paused until %s"
#~ msgstr "Backup pausiert bis %s"

#~ msgid "Backup is healthy"
#~ msgstr "Backup ist fehlerfrei"

#~ msgid "Restore is stale"
#~ msgstr "Wiederherstellung ist veraltet"

#~ msgid "Backup is not healthy"
#~ msgstr "Backup ist nicht fehlerfrei"

#~ msgid "Completed successfully on %s."
#~ msgstr "Erfolgreich abgeschlossen am %s."

#~ msgid ""
#~ "Failed on %s\n"
#~ "%s"
#~ msgstr ""
#~ "Fehlgeschlagen am %s\n"
#~ "%s"

#~ msgid "Running in background and using system resources."
#~ msgstr "Wird im Hintergrund ausgeführt und verwendet Systemressourcen."

#~ msgid ""
#~ "Started in background on %s, but "
#~ "is currently stale an may use "
#~ "system resources."
#~ msgstr ""
#~ "Gestartet im Hintergrund am %s, ist "
#~ "aber derzeit veraltet und kann "
#~ "Systemressourcen verwenden."

#~ msgid ""
#~ "Interrupted on %s. May be caused "
#~ "by computer standby or manual "
#~ "interruption."
#~ msgstr ""
#~ "Unterbrochen am %s. Kann durch "
#~ "Computer-Standby oder manuelle Unterbrechung "
#~ "verursacht worden sein."

#~ msgid ""
#~ "Initial backup need to be started. "
#~ "You may take time to configure "
#~ "your parameters and start your initial"
#~ " backup manually."
#~ msgstr ""
#~ "Das erste Backup muss gestartet werden."
#~ " Sie können sich Zeit nehmen, Ihre"
#~ " Parameter zu konfigurieren und Ihr "
#~ "erstes Backup manuell zu starten."

#~ msgid "Enter user account information for running this tasks."
#~ msgstr "Geben Sie die Benutzerkontodaten ein, um diese Aufgaben auszuführen."

#~ msgid "Password:"
#~ msgstr "Passwort:"

#~ msgid "OK"
#~ msgstr "OK"

#~ msgid "Home"
#~ msgstr "Startseite"

#~ msgid "Schedule Backup"
#~ msgstr "Backup planen"

#~ msgid "Add ..."
#~ msgstr "Hinzufügen ..."

#~ msgid "Remove pattern"
#~ msgstr "Muster entfernen"

#~ msgid "Restore your data"
#~ msgstr "Stelle deine Daten wieder her"

#~ msgid ""
#~ "Through your online account, accessible "
#~ "via a web browser, you can perform"
#~ " partial recovery by selecting specific "
#~ "files or folders to restore from "
#~ "your backup.\n"
#~ "\n"
#~ "You have total control over the "
#~ "items you wish to recover, enabling "
#~ "targeted and rapid restoration without "
#~ "having to restore the entire system."
#~ msgstr ""
#~ "Über Ihr Online-Konto, das über "
#~ "einen Webbrowser zugänglich ist, können "
#~ "Sie eine partielle Wiederherstellung "
#~ "durchführen, indem Sie bestimmte Dateien "
#~ "oder Ordner aus Ihrem Backup auswählen."
#~ "\n"
#~ "\n"
#~ "Sie haben die totale Kontrolle über "
#~ "die Elemente, die Sie wiederherstellen "
#~ "möchten, und können so gezielt und "
#~ "schnell wiederherstellen, ohne das gesamte "
#~ "System wiederherstellen zu müssen."

#~ msgid "Full restoration"
#~ msgstr "Komplette Wiederherstellung"

#~ msgid ""
#~ "This allows you to restore your "
#~ "entire data set from a backup, "
#~ "including your previously backed-up "
#~ "files and folders.\n"
#~ "\n"
#~ "This method is ideal for situations "
#~ "where you need to restore your "
#~ "entire system in the event of "
#~ "hardware failure, total data loss or "
#~ "migration to a new device."
#~ msgstr ""
#~ "Hiermit können Sie Ihren gesamten "
#~ "Datensatz aus einem Backup wiederherstellen,"
#~ " einschließlich Ihrer zuvor gesicherten "
#~ "Dateien und Ordner.\n"
#~ "\n"
#~ "Diese Methode ist ideal für Situationen,"
#~ " in denen Sie Ihr gesamtes System "
#~ "wiederherstellen müssen, beispielsweise bei "
#~ "Hardwareausfällen, einem Totalverlust von "
#~ "Daten oder der Migration auf ein "
#~ "neues Gerät."

#~ msgid ""
#~ "Here, you have the power to choose"
#~ " which files you want to include "
#~ "in your full restore process. By "
#~ "toggling the files on or off, you"
#~ " can customize the restoration to "
#~ "suit your specific needs."
#~ msgstr ""
#~ "Hier können Sie auswählen, welche "
#~ "Dateien Sie in den vollständigen "
#~ "Wiederherstellungsprozess einbeziehen möchten. Indem"
#~ " Sie die Dateien ein- und "
#~ "ausschalten, können Sie die Wiederherstellung"
#~ " an Ihre Bedürfnisse anpassen."

#~ msgid "Loading"
#~ msgstr "Lädt"

#~ msgid ""
#~ "Selected files will be restore with "
#~ "latest data. Existing files will be "
#~ "deleted permanently."
#~ msgstr ""
#~ "Ausgewählte Dateien werden mit den "
#~ "aktuellsten Daten wiederhergestellt. Vorhandene "
#~ "Dateien werden dauerhaft gelöscht."

#~ msgid "I understand the risk"
#~ msgstr "Ich verstehe das Risiko"

#~ msgid "Schedule backup"
#~ msgstr "Backup planen"

#~ msgid "Configure when you want your backup to take place."
#~ msgstr "Konfigurieren Sie, wann Ihr Backup stattfinden soll."

#~ msgid "Suspended"
#~ msgstr "Angehalten"

#~ msgid ""
#~ "This feature lets you pause backup "
#~ "operations for 24 hours. Ideal when "
#~ "you need to reduce the use of "
#~ "system resources or free up bandwidth"
#~ " for other activities."
#~ msgstr ""
#~ "Mit dieser Funktion können Sie "
#~ "Backup-Vorgänge für 24 Stunden anhalten."
#~ " Ideal, wenn Sie die Nutzung von "
#~ "Systemressourcen reduzieren oder Bandbreite "
#~ "für andere Aktivitäten freigeben müssen."

#~ msgid "Advance Options"
#~ msgstr "Erweiterte Optionen"

#~ msgid ""
#~ "This feature allows Minarca to run "
#~ "scheduled backup tasks regardless of "
#~ "whether a user is currently logged "
#~ "on to the system or not. This "
#~ "is particularly useful for server."
#~ msgstr ""
#~ "Diese Funktion ermöglicht es Minarca, "
#~ "geplante Backup-Aufgaben auszuführen, "
#~ "unabhängig davon, ob ein Benutzer "
#~ "derzeit bei dem System angemeldet ist"
#~ " oder nicht. Dies ist besonders "
#~ "nützlich für Server."

#~ msgid "Check now"
#~ msgstr "Jetzt überprüfen"

#~ msgid "Check for update at startup"
#~ msgstr "Beim Start auf Updates überprüfen"

#~ msgid "Your version may be upgraded"
#~ msgstr "Ihre Version kann aktualisiert werden"

#~ msgid "Cannot check for updates. Try again later."
#~ msgstr ""
#~ "Updates können nicht überprüft werden. "
#~ "Versuchen Sie es später noch einmal."

#~ msgid ""
#~ "Allows you to easily verify if "
#~ "there are any new software updates "
#~ "available."
#~ msgstr ""
#~ "Ermöglicht Ihnen, einfach zu überprüfen, "
#~ "ob neue Softwareupdates verfügbar sind."

#~ msgid "Notification"
#~ msgstr "Benachrichtigung"

#~ msgid ""
#~ "To change your notification preferences "
#~ "and be notified of problems, log "
#~ "in to your online account."
#~ msgstr ""
#~ "Um Ihre Benachrichtigungseinstellungen zu "
#~ "ändern und über Probleme benachrichtigt "
#~ "zu werden, melden Sie sich bei "
#~ "Ihrem Online-Konto an."

#~ msgid "Disconnect the backup"
#~ msgstr "Backup trennen"

#~ msgid ""
#~ "When you disconnect this computer, the"
#~ " backup process will no longer work."
#~ msgstr ""
#~ "Wenn Sie diesen Computer trennen, "
#~ "funktioniert der Backup-Prozess nicht "
#~ "mehr."

#~ msgid "Log me in"
#~ msgstr "Anmelden"

#~ msgid "Remote Minarca server"
#~ msgstr "Remote Minarca Server"

#~ msgid "e.g.: https://www.servername.com"
#~ msgstr "z.B.: https://www.servername.de"

#~ msgid ""
#~ "If two-factor authentication is enabled"
#~ " on your account, use an Access "
#~ "Token."
#~ msgstr ""
#~ "Wenn die Zwei-Faktor-Authentifizierung "
#~ "für Ihr Konto aktiviert ist, verwenden"
#~ " Sie einen Zugriffs-Token."

#~ msgid "Repository name"
#~ msgstr "Repository Name"

#~ msgid "Sign in"
#~ msgstr "Anmelden"

#~ msgid ""
#~ "To configure Minarca to backup your "
#~ "data, you must provide URL to "
#~ "Minarca server. This information should "
#~ "be provided by your system "
#~ "administrator."
#~ msgstr ""
#~ "Um Minarca zur Sicherung Ihrer Daten "
#~ "zu konfigurieren, müssen Sie die URL "
#~ "zum Minarca-Server angeben. Diese "
#~ "Informationen sollten von Ihrem "
#~ "Systemadministrator bereitgestellt werden."

#~ msgid "View my account online"
#~ msgstr "Mein Konto online ansehen"

#~ msgid "Status: "
#~ msgstr "Status: "

